[install]
linker = "isolated"
exact = true
minimumReleaseAge = 259200 # 3 días

[run]
bun = true
silent = true

[test]
coverage = true
coveragePathIgnorePatterns = [
  "src/lib/db/schema.ts",
  "src/lib/db/migrations",
]
